### ISSUE TITLE
Developer testing mode

### ISSUE THREAD

**Issue by zmughal** [zmughal/pdl#4]
Don't overwrite code gen files if they are the same so that `make` will not have to rebuild frequently. Simple sketch of the flow:

``` shell
codegen $FILE.in > $FILE.new; md5sum $FILE $FILE.new; mv $FILE.new $FILE
```

Also, make sure all the files loaded during test are from the build directory rather than a pre-existing PDL install. Use `strace` to verify this.

**Comment by mohawk2** [comment]
I think this is solving the wrong problem; why not just use regular make dependencies to avoid unnecessary rebuilds?

**Comment by zmughal** [comment]
Because `make` will use the timestamp and the writing a file via the codegen changes that, right?

**Comment by mohawk2** [comment]
It does indeed. Why is it being run in the first place, though?

**Comment by zmughal** [comment]
It's just to help speed up the feedback loop between changing a single function and the build.

**Comment by mohawk2** [comment]
I don't know what precisely you meant by codegen, by the way. Is that the `*.pd` -> XS etc step?

**Comment by zmughal** [comment]
Yes

**Comment by zmughal** [comment]
Moved to https://github.com/PDLPorters/pdl/issues/10
